crud2pro/urls.py
from django.contrib import admin
from django.urls import path
from testapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.emp),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),


]

testapp/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=12)

    class Meta:
        db_table = 'employee'

testapp/forms.py
from django import forms
from testapp.models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

testapp/views.py
from django.shortcuts import render,redirect
from testapp.forms import EmployeeForm
from testapp.models import Employee
# Create your views here.

# employees entry
def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request,'testapp/index.html',{'form':form})

# all employees show
def show(request):
    employees = Employee.objects.all()
    return render(request,'testapp/show.html',{'employees':employees})

# employee edit
def edit(request,id):
    employee = Employee.objects.get(id=id)
    return render(request,'testapp/edit.html',{'employee':employee})

# employee update
def update(request,id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST,instance=employee)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request,'testapp/edit.html',{'employee':employee})

# employee delete
def delete(request,id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect('/show')

templates/testapp/edit.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Update</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous">
  </head>
  <body>
    <form class="post-form" action="/update/{{employee.id}}" method="post">
      {% csrf_token %}
      <div class="container"><br>
        <div class="form-group-row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Update Details</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Id:</label>
          <div class="col-sm-4">
            <input type="text" name="eid" id="id_eid" required maxlength="20"value="{{employee.eid}}"/>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Name:</label>
          <div class="col-sm-4">
          <input type="text" name="ename" id="id_ename" required maxlength="100"value="{{employee.ename}}"/>
      </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
        <input type="text" name="eemail" id="id_eemail" required maxlength="254"value="{{employee.eemail}}"/>
    </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Employee Contact:</label>
      <div class="col-sm-4">
      <input type="text" name="econtact" id="id_econtact" required maxlength="15"value="{{employee.econtact}}"/>
  </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1" col-form-label></label>
    <div class="col-sm-4">
      <button type="submit" class="btn btn-success"name="button">Update</button>
      </div>
    </div>
  </div>
    </form>
  </body>
</html>

templates/testapp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous">
  </head>
  <body>
    <form class="post-form" method="POST"action="/">
      {% csrf_token %}
      <div class="container">
        <br>
        <div class="form-group-row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Enter Employee Details</h3>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Id:</label>
          <div class="col-sm-4">
            {{form.eid}}
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Name:</label>
          <div class="col-sm-4">
            {{form.ename}}
      </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          {{form.eemail}}
    </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Employee Contact:</label>
      <div class="col-sm-4">
        {{form.econtact}}
  </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-1" col-form-label></label>
    <div class="col-sm-4">
      <button type="submit" class="btn btn-primary"name="button">Submit</button>
      </div>
    </div>
  </div>
    </form>
  </body>
</html>

templates/testapp/show.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Employee Records</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
    crossorigin="anonymous">
  </head>
  <body>
    <center><caption><h2><b>Employee Management System</b></h2></caption></center>
  <table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
      <tr>
        <th>Employee Id</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for employee in employees %}
      <tr>
        <td>{{employee.eid}}</td>
        <td>{{employee.ename}}</td>
        <td>{{employee.eemail}}</td>
        <td>{{employee.econtact}}</td>
        <td><a href="/edit/{{employee.id}}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
        <a style="color:red" href="/delete/{{employee.id}}">Delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <br
  <center><a href="/" class="btn btn-primary">Add New Record</a></center>
  </body>
</html>